wireframes/urls.py
# -*- coding: utf-8 -*-
from django.urls import path, include
from wireframes.views import create, edit, save

urlpatterns = [
    #url(r'^$', 'home', name="wireframes-home"),
    path(r'^create/$', create, name="wireframes-create"),
    path(r'^(?P<wireframe_id>[0-9]+)/edit/$', edit, name="wireframes-edit"),
    path(r'^(?P<wireframe_id>[0-9]+)/save/$', save, name="wireframes-save"),
]

wireframes/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User

class Project(models.Model):
    """(Project description)"""

    admin = models.ForeignKey(User, related_name='selfs_as_admin', null=True, on_delete=models.CASCADE)
    members = models.ManyToManyField(User, related_name='selfs_as_member')

    name = models.CharField(blank=False, max_length=255)
    grid_width = models.PositiveIntegerField(default="50")
    grid_spacing = models.PositiveIntegerField(default="10")
    grid_columns = models.PositiveIntegerField(default="16")

    def total_width(self):
        return self.grid_columns * self.grid_width + (self.grid_spacing * self.grid_columns-1)

    def __str__(self):
        return "%s" % (self.name)

    def get_absolute_url(self):
        return 'not done'

    def save(self):
        super(Project, self).save()

class Wireframe(models.Model):
    """(Project description)"""

    author = models.ForeignKey(User, null=True, on_delete=models.DO_NOTHING)
    project = models.ForeignKey(Project, null=True, on_delete=models.DO_NOTHING)
    name = models.CharField(blank=False, max_length=255)
    creation_date = models.DateTimeField(auto_now=True)
    #model = models.ForeignKey(Wireframe, null=True)
    grid_width = models.PositiveIntegerField(default="50")
    grid_spacing = models.PositiveIntegerField(default="10")
    grid_columns = models.PositiveIntegerField(default="16")

    def total_width(self):
        return (self.grid_columns * self.grid_width) + (self.grid_spacing *
                                        (self.grid_columns-1))


    def __str__(self):
        return "wireframe %s %d" % (self.name, self.id)

    def save(self):
        super(Wireframe, self).save()

class Component(models.Model):
    """(Component description)"""

    author = models.ForeignKey(User, null=True, blank=True, on_delete=models.DO_NOTHING)
    project = models.ForeignKey(Project, null=True, blank=True, on_delete=models.DO_NOTHING)
    name = models.CharField(blank=False, max_length=255)
    creation_date = models.DateTimeField(auto_now=True)

    default_content = models.TextField(blank=True)
    javascript = models.TextField()
    css = models.TextField(blank=True)

    def css_out(self):
        rules = ""
        r_list = self.css.strip().split('}')
        for r in r_list:
            if r.strip():
                rules += ".component-%d %s }\n" % (self.id , r.strip())
        return rules

    def __str__(self):
        return "Component %s" % (self.name)

class Revision(models.Model):

    author = models.ForeignKey(User, null=True, on_delete=models.DO_NOTHING)
    wireframe = models.ForeignKey(Wireframe, on_delete=models.DO_NOTHING)
    creation_date = models.DateTimeField(auto_now=True)
    content = models.TextField()

    def __str__(self):
        return "%s" % (self.wireframe)

    def save(self):
        super(Revision, self).save()

wireframes/forms.py
from wireframes.models import Wireframe, Project
from django.forms import ModelForm
from django import forms

"""class CreateWireframeForm(DecoratingModelForm):
    class Meta:
        model=Wireframe
        fields=('name', 'project')"""

class CreateWireframeForm(ModelForm):
    name = forms.CharField(initial="New wireframe")
    grid_width = forms.IntegerField(min_value=12, initial=70)
    grid_spacing = forms.IntegerField(min_value=0, initial=10)
    grid_columns = forms.IntegerField(min_value=1, max_value=100, initial=12)
    class Meta:
        model=Wireframe
        fields=('name', 'grid_width', 'grid_spacing', 'grid_columns')

class CreateProjectForm(ModelForm):
    name = forms.CharField(initial="boum")
    grid_width = forms.IntegerField(min_value=12)
    grid_spacing = forms.IntegerField(min_value=0)
    grid_columns = forms.IntegerField(min_value=1, max_value=100)
    class Meta:
        model=Project
        fields=('name', 'grid_width', 'grid_spacing', 'grid_columns')

wireframes/views.py
from wireframes.models import Wireframe, Revision, Component, Project
from wireframes.forms import CreateWireframeForm
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.shortcuts import render

def home(request):
    if request.POST:
        form = CreateWireframeForm(request.POST)
        if form.is_valid():
            wireframe = form.save()
            return HttpResponseRedirect(reverse('wireframes-edit',
                    args=[wireframe.id]))
    else:
        form = CreateWireframeForm()
    return render(request, 'wireframes/home.html', locals())

def create(request, project_id):
    project = Project.objects.get(pk=int(project_id))
    wireframe = Wireframe(author=request.user, project=project)
    if request.POST:
        form = CreateWireframeForm(request.POST, instance=wireframe)
        if form.is_valid():
            wireframe = form.save()
            return HttpResponseRedirect(reverse('wireframes-edit',
                args=None, kwargs={"project_id":int(wireframe.project.id),
                "wireframe_id":int(wireframe.id)}))
    else:
        form = CreateWireframeForm(instance=wireframe)
    return render(request, 'wireframes/create.html', locals())

def edit(request, wireframe_id):
    wireframe = Wireframe.objects.get(pk=int(wireframe_id))
    try:
        last_revision = Revision.objects.filter(
                wireframe=wireframe).latest('creation_date')
    except Revision.DoesNotExist:
        pass
    components = Component.objects.all()
    return render(request, 'wireframes/edit.html', locals())

def save(request, wireframe_id):
    wireframe = Wireframe.objects.get(pk=int(wireframe_id))
    revision = Revision(wireframe=wireframe)
    revision.content = request.POST['content']
    revision.save()
    return HttpResponse('Wireframe saved')

wireframes/templates/wireframes/base.html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="Content-Language" content="en" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Wireframe online</title>
<script type="text/javascript" src="{{MEDIA_URL}}wireframes/js/jquery.js"></script>
<script type="text/javascript" src="{{MEDIA_URL}}wireframes/js/commands.jquery.js"></script>
<script type="text/javascript" src="{{MEDIA_URL}}wireframes/js/drag.js"></script>
<script type="text/javascript" src="{{MEDIA_URL}}wireframes/js/wireframe.js"></script>
<script type="text/javascript" src="{{MEDIA_URL}}wireframes/js/ui.core.js"></script>
<script type="text/javascript" src="{{MEDIA_URL}}wireframes/js/ui.selectable.js"></script>
<link rel="stylesheet" href="{{MEDIA_URL}}wireframes/css/style.css" type="text/css" media="screen" title="" />
<style>
{% block extra_css %}{% endblock %}
</style>
</head>
<body>

<div id="header">
    {% block header %}

    {% endblock %}
</div>

<div id="content" class="{% block body_class %}{% endblock %}">
{% block content %}

{% endblock %}
</div>
</body>
</html>

wireframes/templates/wireframes/create.html
{% extends "base.html" %}

{% block header %}
<h1>Wireframe</h1>
<p class="breadcrumb">Project <strong>{{ project.name }}</strong> &raquo; Create a new wireframe</p>
{% endblock %}

{% block content %}
<form action="." method="post" class="simpleform">
<fieldset>
    <legend>Create a new wireframe</legend>
    {{ form.as_p }}
    <p><input type="submit" value="{% trans 'Create this wireframe' %}" class="submit"></p>
    </fieldset>
</form>
{% endblock %}

wireframes/templates/wireframes/edit.html
{% extends "wireframes/base.html" %}
{% load wire_tags i18n %}
{% block extra_css %}
{% for c in components %}{% if c.css %}{{ c.css_out }}{% endif %}{% endfor %}
{% endblock %}

{% block header %}
<h1>Wireframe</h1>
<p>{{ wireframe.name }}</strong></p>
{% endblock %}

{% block body_class %}wireframe-edit{% endblock %}

{% block content %}
<div id="menu">
    <label>
    <select id="create-component" name="create-component">
        <option value="0">{% trans "Create" %}</option>
        {% for c in components %}
        <option value="{{ c.id }}">{{ c.name }}</option>
        {% endfor %}
    </select>
    </label>

    <input type="button" value="Undo" id="undo" />
    <input type="button" value="Redo" id="redo" />
    <input type="button" value="Save" id="save" />
    
    <span id="message"></span>
</div>
    <div id="toolbox" style="position:absolute;left:{{ wireframe.total_width|add:50 }}px">
        <h2 id="properties-title"></h2>
        <div id="properties"></div>
    </div>

    <div id="editor" style="width:{{ wireframe.total_width }}px">
    <input type="text" id="editor-focus" style="position:absolute;left:-500px;">
    {% if last_revision %}
        {{ last_revision.content|safe }}
    {% else %}
        <div id="grid-view"></div>
    {% endif %}
    </div>
</div>


<script type="text/javascript">
nb_columns = {{ wireframe.grid_columns }};
columns_width = {{ wireframe.grid_width }};
columns_spacing = {{ wireframe.grid_spacing }};
$(document).ready( function() {
    $('#editor').easydrag({
        grid_width:{{ wireframe.grid_width }},
        grid_spacing:{{ wireframe.grid_spacing }}
    });
});

$('#save').click( function(event) {
    $.post(
        "{% url 'wireframes-save' wireframe.id %}",
        {'content':$('#editor').html()},
        function(data){
            $("#message").text(data).show().fadeOut(3000);
        }
    );
});

function get_component_by_id(id) {

    var components = {};
    {% for c in components %}
    var c = {{ c.javascript|safe }};
    c.default_content = "{{ c.default_content|escape_javascript_string }}";
    c.name = "{{ c.name }}";
    components["component-{{ c.id }}"] = c;
    {% endfor %}

    if(components["component-"+id]) {
        return components["component-"+id]
    }

    return {};
};

function create_component(t, l, id, content, title, w) {

    var c = get_component_by_id(id);
    if(!w)
        w = 200;
    if(!title)
        title = c.name;
    if(!t)
        t=0;
    if(!l)
        l=0;
    
    var block = '<div class="block snap-to-grid component-'+ id +'" \
        style="width: '+w+'px; top: '+t+'px; left:'+l+'px;"" title="'+ title +'">\
        <div class="resize">r</div>\
        <div class="content">' + c.default_content + '</div>\
        <div class="display">' + c.display(c.default_content) + '</div>\
    </div>'
    $('#editor').append($(block));
};

$('#create-component').change(function() {
    var index = this.selectedIndex;
    if( index!=0 ) {
        var value = this.options[index].value;
        create_component(0, 0, value);
        this.selectedIndex = 0;
    }
});

</script>

{% endblock %}

wireframes/templates/wireframes/home.html
{% extends "wireframes/base.html" %}
{% load i18n %}
{% block header %}
<h1>Wireframe</h1>
<p>Create a new wireframe</p>
{% endblock %}


{% block content %}
<form action="" method="post" id="create-wireframe">
<fieldset>
    <legend>Create a new wireframe</legend>
    {{ form.name.errors }}
    <p><label for="id_name">Wireframe name</label> {{ form.name }}</p>
    {{ form.grid_width.errors }}
    <p class="number"><label for="id_grid_width">Columns width</label> {{ form.grid_width }}px</p>
    {{ form.grid_spacing.errors }}
    <p class="number"><label for="id_grid_spacing">Columns spacing</label> {{ form.grid_spacing }}px</p>
    {{ form.grid_columns.errors }}
    <p class="number"><label for="id_grid_columns">Number of columns</label> {{ form.grid_columns }}</p>
    <p class="number"><label for="total-width">Total width</label> <input id="total-width" type="text" disabled="disabled" class="textinput" name="total-width" />px</p>
    <p><input type="submit" value="{% trans 'Create this wireframe' %}" class="submit"></p>
    </fieldset>
</form>

<div id="rule">
    <h2>Grid preview</h2>
    <div style="width:795px" id="width-800">800 px</div>
    <div style="width:219px" id="width-1024">1024 px</div>
    <div style="width:171px" id="width-1200">1200 px</div>
</div>

<div id="grid-preview"></div>

<script type="text/javascript">
$(document).ready( function() {

    var drawGrid = function() {
        var gv = $('#grid-preview');
        gv.empty();
        var parseInput = function (query, min, max) {
            var val = parseInt($(query).val());
            if( isNaN( val) )
                val = 0
            if(max && val > max)
                val=max;
            if(min && val < min)
                val=min;
            $(query).val(val)
            return val;
        }
        var nb_columns = parseInput('#id_grid_columns', 1, 100);
        var columns_width = parseInput('#id_grid_width', 12);
        var columns_spacing = parseInput('#id_grid_spacing', 0);
        var total = nb_columns * columns_width + (nb_columns-1) * columns_spacing;
        $('#total-width').val(total);
        for(var i=0; i<nb_columns-1;i++) {
            gv.append($('<div class="columns" style="width:'+columns_width+'px"></div><div class="spacing" style="width:'+columns_spacing+'px"></div>'));
        }
        gv.append($('<div class="columns" style="width:'+columns_width+'px"></div>'));
        var display_warning = function (w) {
            if(total > w-50)
                $('#width-'+w).addClass('warning');
            else
                $('#width-'+w).removeClass('warning');
        }
        display_warning(800);
        display_warning(1024);
        display_warning(1200);
    }
    drawGrid();
    $('input').change(drawGrid);

});
</script>



{% endblock %}

wireframes/templates/wireframes/home_anonymous.html
{% extends "base.html" %}

{% block header %}
<h1>Wireframe online</h1>
<p>You are not logged</p>
{% endblock %}

{% block content %}

<h2><a href="admin/">Join now</a></h2>
<h2><a href="">Test the product online</a></h2>

{% endblock %}